---
postgresql_version: 18
postgresql_packages:
  - "postgresql-{{ postgresql_version }}"
  - "postgresql-client-{{ postgresql_version }}"

postgresql_apt_key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
postgresql_apt_keyring: /usr/share/keyrings/postgresql-archive-keyring.gpg
postgresql_apt_repo: "deb [signed-by={{ postgresql_apt_keyring }}] http://apt.postgresql.org/pub/repos/apt {{ ansible_facts['distribution_release'] }}-pgdg main"

postgresql_service_enabled: true
postgresql_service_state: started

postgresql_data_dir: /data/postgresql
postgresql_listen_addresses: "*"
postgresql_pgbench_db: pgcloudbench
postgresql_configuration: {}
postgresql_nofile_limit: 65536
postgresql_pgbench_password: ""
